version: '3.8'

services:
  app:
    build: .
    container_name: syncsentinel
    restart: unless-stopped
    environment:
      # Config PostgreSQL externo
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_SCHEMA
      # Config SQL Server hosts
      - HOST_GAINS
      - HOST_REPLICA
      - HOST_EPICOR
      - HOST_CL
      # Config SQL Server databases
      - MSSQL_DB_GAINS
      - MSSQL_DB_REPLICA
      - MSSQL_DB_EPICOR
      - MSSQL_DB_CL
      # Config SQL Server credentials
      - MSSQL_USER
      - MSSQL_PASS
      # App configuration
      - APP_NAME
      - APP_ENV
      - MONITOR_START_TIME
      - MONITOR_END_TIME
      - CHECK_INTERVAL_SECONDS
      # Notifications
      - SLACK_WEBHOOK_URL
      # Logging
      - LOG_ERROR_FILE
      # Query configuration
      - START_DATE_DAYS_BACK
    volumes:
      - /home/boxadm/infra/syncsentinel/logs:/app/logs
      - /home/boxadm/infra/syncsentinel/data:/app/data
    networks:
      - syncsentinel-net

networks:
  syncsentinel-net:
    driver: bridge
